name: animalswitcher
description: A simple Flutter app that switches text between 'Cat' and 'Dog' when clicked, using the Cubit pattern for state management.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true